image:
  repository: javachen/jira-software:8.7.0
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - jira.wesine.com.cn
    - jira.test.wesine.com.cn
  tls:
    - secretName: jira-test-wesine-com-cn-cert
      hosts:
        - jira.wesine.com.cn
        - jira.test.wesine.com.cn

persistence:
  enabled: true
  storageClass: "ceph-rbd"
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 2 
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
