keycloak:
  persistence:
    deployPostgres: false
    dbVendor: postgres
    dbName: keycloak
    dbHost: 192.168.1.111
    dbPort: 5432 
    dbUser: postgres
    dbPassword: "123456"

  password: admin123

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - keycloak.wesine.com.cn
      - keycloak.test.wesine.com.cn
