# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  ## The official gitea image, change tag to use a different version.
  ## ref: https://hub.docker.com/r/gitea/gitea/tags/
  ##
  repository: gitea/gitea
  tag: 1.10.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

expose:
  # Set the way how to expose the service. Set the type as "ingress","clusterIP","LoadBalancer"
  # or "nodePort" and fill the information in the corresponding
  # section
  type: ingress
  tls:
    enabled: false
    # Fill the name of secret if you want to use your own TLS certificate
    # and private key. The secret must contain keys named tls.crt and
    # tls.key that contain the certificate and private key to use for TLS
    # The certificate and private key will be generated automatically if
    # it is not set
    secretName: ""
  ingress:
    enabled: false
    host: gitea.cluster.local
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      # kubernetes.io/tls-acme: "true"
  clusterIP:
    # The name of ClusterIP service
    # name: gitea
    ports:
      # The service port gitea listens on when serving with SSH
      ssh: 22
      # The service port gitea listens on when serving with HTTP
      http: 80
  nodePort:
    # The name of NodePort service
    # name: gitea
    ports:
      ssh:
        # The service port gitea listens on when serving with SSH
        port: 22
        # The node port gitea listens on when serving with SSH
        # nodePort: 30002
      http:
        # The service port gitea listens on when serving with HTTP
        port: 80
        # The node port gitea listens on when serving with HTTP
        # nodePort: 30003
  loadBalancer:
    annotations: []
    # The name of LoadBalancer service
    # name: gitea
    ports:
      # The service port gitea listens on when serving with SSH
      ssh: 22
      # The service port gitea listens on when serving with HTTP
      http: 80


## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: false

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## rabbitmq data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi

extraContainers: |

## additional volumes, e. g. for secrets used in an extraContainers.
##
extraVolumes: |

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
