# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: atlassian/jira-software:8.3.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

expose:
  # Set the way how to expose the service. Set the type as "ingress","clusterIP","loadBalancer"
  # or "nodePort" and fill the information in the corresponding section
  type: ingress
  ingress:
    enabled: true
    tls:
      enabled: false
      # Fill the name of secret if you want to use your own TLS certificate
      # and private key. The secret must contain keys named tls.crt and
      # tls.key that contain the certificate and private key to use for TLS
      # The certificate and private key will be generated automatically if
      # it is not set
      secretName: ""
    host: jira.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      # kubernetes.io/tls-acme: "true"
  clusterIP:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
  nodePort:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
        #nodePort: 38080
  loadBalancer:
    annotations: []
    ports:
      - name: http
        port: 8080
        targetPort: 8080


## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  enabled: false

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## rabbitmq data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 5Gi

extraContainers: |

## additional volumes, e. g. for secrets used in an extraContainers.
extraVolumes: |

securityContext: {}
  #runAsUser: 0

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}