apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "app.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "app.labels" . | indent 8 }}
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}   
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- with .Values.hostAliases }}
      hostAliases:
{{ toYaml . | indent 8 }}
{{- end }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: "/var/atlassian/application-data/confluence"
            - name: home
              mountPath: "/opt/atlassian/confluence"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: confluence
        - name: home
          emptyDir: {}
