apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  {{- with .Values.expose.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
  labels:
{{ include "app.labels" . | indent 4 }}
{{- if or (eq .Values.expose.type "clusterIP") (eq .Values.expose.type "ingress") }}
{{- $clusterIP := .Values.expose.clusterIP }}
spec:
  type: ClusterIP
  ports:
{{- with $clusterIP.ports }}
{{ toYaml . | indent 4 }}
{{- end }}

{{- else if eq .Values.expose.type "nodePort" }}
{{- $nodePort := .Values.expose.nodePort }}
spec:
  type: NodePort
  ports:
{{- with $clusterIP.ports }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
{{- with $clusterIP.ports }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
