{{- if eq .Values.tls "ingress" -}}
  {{- if eq .Values.ingress.tls.source "letsEncrypt" -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ template "rancher.fullname" . }}-letsencrypt-{{ .Values.letsEncrypt.environment }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  acme:
    {{- if eq .Values.letsEncrypt.environment "prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    {{- if eq .Values.letsEncrypt.environment "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.letsEncrypt.email }}
    privateKeySecretRef:
      name: {{ template "rancher.fullname" . }}-letsencrypt-{{ .Values.letsEncrypt.environment }}
{{- if .Values.letsEncrypt.solvers  }}   
    solvers:  
{{ toYaml .Values.letsEncrypt.solvers | indent 4 }}
{{- else }}
    http01: {}
{{- end }}    
  {{- end -}}
{{- end -}}
