apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-webhook.fullname" . }}
  labels:
{{ include "example-webhook.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "example-webhook.name" . }}
    release: {{ .Release.Name }}
